resolver: nightly-2019-03-17

packages:
  - '.'

extra-deps:
  - git:     https://github.com/Taiji-pipeline/bio-experiments.git
    commit:  5fd7472babf427606058594c089abf689b7b89f4

  - git:     https://github.com/kaizhang/bioinformatics-toolkit.git
    commit:  942af76592a4ac9a708914efcf0c91873d4f89b9
    subdirs: 
      - bioinformatics-toolkit

  - HsHTSLib-1.9.2
  - clustering-0.4.1
