resolver: nightly-2019-05-25

packages:
  - '.'

extra-deps:
  - git:     https://github.com/Taiji-pipeline/bio-experiments.git
    commit:  5fd7472babf427606058594c089abf689b7b89f4

  - bioinformatics-toolkit-0.9.3.1
  - HsHTSLib-1.9.2
  - clustering-0.4.1