resolver: nightly-2019-03-17

packages:
  - '.'

extra-deps:
  - git:     https://github.com/Taiji-pipeline/bio-experiments.git
    commit:  049f1e93b611c01e9afc2b6a1010802e07a39af5
  - bioinformatics-toolkit-0.7.0
  - HsHTSLib-1.9.2
  - clustering-0.4.1
