resolver: lts-14.4

allow-newer: true

packages:
  - '.'

extra-deps:
  - git:     https://github.com/Taiji-pipeline/bio-experiments.git
    commit:  5fd7472babf427606058594c089abf689b7b89f4

  - bioinformatics-toolkit-0.9.0
  - HsHTSLib-1.9.2
  - clustering-0.4.1
  - ftp-client-conduit-0.5.0.4
  - ftp-client-0.5.1.1