resolver: nightly-2019-03-17

packages:
  - '.'

extra-deps:
  - git:     https://github.com/Taiji-pipeline/bio-experiments.git
    commit:  5fd7472babf427606058594c089abf689b7b89f4
  - bioinformatics-toolkit-0.7.0
  - HsHTSLib-1.9.2
  - clustering-0.4.1
